### ISSUE TITLE
请问下py执行顺序是什么，还有所用bert预训练模型在哪里下载？

### ISSUE THREAD

**Issue by yandong667** [bearbro/ccks2020#1]

**Comment by bearbro** [comment]
bert的预模型百度一下一大堆,https://github.com/ymcui/Chinese-BERT-wwm#%E4%B8%AD%E6%96%87%E5%9F%BA%E7%BA%BF%E7%B3%BB%E7%BB%9F%E6%95%88%E6%9E%9C
这个是哈工大讯飞联合实验室的

写了两种思路:
model1是先事件分类,再ner, 
model2是先ner,再分类
执行顺序,看文件名就知道了

**Comment by yandong667** [comment]
好的谢谢您



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月13日(周四) 中午12:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bearbro/ccks2020] 请问下py执行顺序是什么，还有所用bert预训练模型在哪里下载？ (#1)




 
bert的预模型百度一下一大堆,https://github.com/ymcui/Chinese-BERT-wwm#%E4%B8%AD%E6%96%87%E5%9F%BA%E7%BA%BF%E7%B3%BB%E7%BB%9F%E6%95%88%E6%9E%9C
 这个是哈工大讯飞联合实验室的
 
写了两种思路:
 model1是先事件分类,再ner,
 model2是先ner,再分类
 执行顺序,看文件名就知道了
